version: '3.8'

services:
  clickhouse:
    build:
      context: ./clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - ./clickhouse/config.xml:/etc/clickhouse-server/config.xml
      - ./clickhouse/users.xml:/etc/clickhouse-server/users.xml
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8123/ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - data-network
    profiles: ["core"]

  superset:
    build:
      context: ./superset
    ports:
      - "8088:8088"
    volumes:
      - superset-data:/app/superset-home   # для метабазы и загруженных файлов
    depends_on:
      clickhouse:
        condition: service_healthy
    networks:
      - data-network
    profiles: ["core"]

networks:
  data-network:
    driver: bridge

volumes:
  clickhouse-data:
  superset-data: